# DBus system config — allows zaios user to talk to all system services
<!DOCTYPE busconfig PUBLIC
 "-//freedesktop//DTD D-BUS Bus Configuration 1.0//EN"
 "http://www.freedesktop.org/standards/dbus/1.0/busconfig.dtd">
<busconfig>
  <policy user="zaios">
    <allow send_destination="*"/>
    <allow send_interface="*"/>
    <allow send_type="*"/>
  </policy>
  <policy group="netdev">
    <allow send_destination="org.freedesktop.NetworkManager"/>
    <allow send_interface="org.freedesktop.NetworkManager"/>
  </policy>
  <policy group="bluetooth">
    <allow send_destination="org.bluez"/>
    <allow send_interface="org.bluez"/>
  </policy>
</busconfig>
