# ZAIos Calamares settings — drives the GUI installer
# SPDX-License-Identifier: GPL-3.0-or-later
#
# This is the top-level config for Calamares. Each module referenced here
# has its own .conf file in modules/<name>.conf

---
# Sequence of install steps shown to the user
sequence:
  - show:
    - welcome
    - locale
    - keyboard
    - partition
    - users
    - summary
  - exec:
    - partition
    - mount
    - unpackfs
    - sources-media
    - machineid
    - fstab
    - locale
    - keyboard
    - localecfg
    - users
    - networkcfg
    - hwclock
    - services-systemd
    - bootloader
    - packages
    - zaios-finalize
    - initramfs
    - removeuser
    - displaymanager
    - umount
  - show:
    - finished

# Show / hide debug in the UI
showDebug: false

# Don't quit (so users can see the success message)
quit-at-end: false

# Theme (use our glassmorphism colors)
branding: zaios
