#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
# zaios-finalize — Calamares module that does ZAIos-specific post-install
# setup. Runs after unpackfs has copied the live rootfs to /target.

import os
import shutil
import calamares
from pathlib import Path

TARGET = calamares.globalstorage.value("rootMountPoint") or "/target"

def pretty_name():
    return "Finalizing ZAIos installation"

def run():
    """Calamares module entry point."""
    config = calamares.job.configuration

    # 1. Write marker file
    marker_path = os.path.join(TARGET, config.get("marker", "/etc/zaios/installed").lstrip("/"))
    os.makedirs(os.path.dirname(marker_path), exist_ok=True)
    with open(marker_path, "w") as f:
        f.write("installed=1\n")
        f.write(f"install_date={__import__('datetime').datetime.now().isoformat()}\n")

    # 2. Update zaios.conf
    zaios_conf = os.path.join(TARGET, "etc/zaios/zaios.conf")
    if os.path.exists(zaios_conf):
        update_config(zaios_conf, config.get("configUpdate", {}))

    # 3. Preserve live session settings
    for src in config.get("preserveFromLive", []):
        src = src.rstrip("/")
        dst = os.path.join(TARGET, src.lstrip("/"))
        if os.path.exists(src):
            os.makedirs(os.path.dirname(dst), exist_ok=True)
            if os.path.isdir(src):
                shutil.copytree(src, dst, dirs_exist_ok=True)
            else:
                shutil.copy2(src, dst)

    # 4. Install GRUB config for disk boot
    install_grub_config()

    # 5. Generate initramfs on the target
    calamares.utils.target_env_call(["sh", "-c",
        "which mkinitcpio && mkinitcpio -P || "
        "which dracut && dracut --regenerate-all --force || "
        "echo 'no initramfs generator found'"])

    return None


def update_config(path, updates):
    """Update INI-style config file with key=value pairs."""
    lines = []
    if os.path.exists(path):
        with open(path, "r") as f:
            lines = f.readlines()

    new_lines = []
    for line in lines:
        stripped = line.strip()
        if "=" in stripped and not stripped.startswith("#"):
            key = stripped.split("=", 1)[0]
            if key in updates:
                new_lines.append(f"{key}={updates[key]}\n")
                del updates[key]
                continue
        new_lines.append(line)

    if updates:
        new_lines.append("\n# Updated by Calamares zaios-finalize\n")
        for k, v in updates.items():
            new_lines.append(f"{k}={v}\n")

    with open(path, "w") as f:
        f.writelines(new_lines)


def install_grub_config():
    """Write /etc/default/grub on the target."""
    grub_default = os.path.join(TARGET, "etc/default/grub")
    os.makedirs(os.path.dirname(grub_default), exist_ok=True)
    with open(grub_default, "w") as f:
        f.write("""# GRUB default - generated by ZAIos Calamares module
GRUB_DEFAULT=0
GRUB_TIMEOUT=5
GRUB_DISTRIBUTOR="ZAIos"
GRUB_CMDLINE_LINUX_DEFAULT="quiet loglevel=3 zaios.installed=1"
GRUB_CMDLINE_LINUX=""

GRUB_PRELOAD_MODULES="part_gpt part_msdos"
GRUB_TERMINAL_INPUT=console
GRUB_GFXMODE=auto
GRUB_GFXPAYLOAD_LINUX=keep

GRUB_DISABLE_RECOVERY=true
GRUB_DISABLE_SUBMENU=y
GRUB_DISABLE_OS_PROBER=true

# EFI
GRUB_EARLY_INITRD_LINUX=""

# Theme
GRUB_BACKGROUND=""
GRUB_THEME=""
""")
