# BlueZ main config
[General]
Name = ZAIos
Class = 0x000540
DiscoverableTimeout = 0
PairableTimeout = 0
AlwaysPairable = true

# A2DP (high-quality audio sink)
[A2DP]
SBCSources=1
MPEG12Sources=0

# Enable HFP for remote microphones
[HFP]
MaxConnections=1
